"""SCIM 2.0 pure helpers: mapping, filter parsing, PATCH normalization, SPC.

Protocol logic with no DB and no HTTP (sod_engine shape): the router stays
thin and everything here is unit-testable in isolation. v1 defects designed
out: the filter parser is fullmatch-anchored (v1's re.match accepted
trailing junk after the quoted value), the SPC is honest (sort/bulk/etag
false - advertised lies designed out), and no phone placeholder exists.
"""
from __future__ import annotations

import re

USER_SCHEMA = "urn:ietf:params:scim:schemas:core:2.0:User"
ERROR_SCHEMA = "urn:ietf:params:scim:api:messages:2.0:Error"
SPC_SCHEMA = "urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig"

PAGE_DEFAULT_COUNT = 100
PAGE_MAX_COUNT = 200


class ScimError(Exception):
    """Protocol-level failure; the router renders it as a SCIM error envelope."""

    def __init__(self, status: int, detail: str):
        super().__init__(detail)
        self.status = status
        self.detail = detail

    def envelope(self) -> dict:
        return {"schemas": [ERROR_SCHEMA], "status": str(self.status), "detail": self.detail}


def service_provider_config() -> dict:
    """Honest capabilities (RFC 7643 8.5): only what /api/scim/v2 serves."""
    return {
        "schemas": [SPC_SCHEMA],
        "patch": {"supported": True},
        "bulk": {"supported": False, "maxOperations": 0, "maxPayloadSize": 0},
        "filter": {"supported": True, "maxResults": PAGE_MAX_COUNT},
        "changePassword": {"supported": False},
        "sort": {"supported": False},
        "etag": {"supported": False},
        "authenticationSchemes": [
            {
                "type": "oauthbearertoken",
                "name": "SCIM Bearer Token",
                "description": "Single installation token generated by an IAG admin.",
                "primary": True,
            }
        ],
        "meta": {"resourceType": "ServiceProviderConfig"},
    }


# EQ-only, one clause, three attribute shapes. fullmatch: v1 anchored only
# the start, so trailing junk after the quoted value was silently accepted.
_FILTER_RE = re.compile(r'(username|emails\.value|externalid)\s+eq\s+"([^"]*)"', re.IGNORECASE)
_FILTER_FIELDS = {"username": "userName", "emails.value": "emails.value", "externalid": "externalId"}


def parse_filter(expr: str | None) -> tuple[str, str] | None:
    """Return (field, value), or None when no filter was supplied.

    Accepts exactly: userName eq "x" | emails.value eq "x" | externalId eq "x"
    (attribute names case-insensitive per RFC 7644). Anything else - other
    operators, other attributes, two clauses, unquoted values, trailing
    junk - is a 400 ScimError.
    """
    if expr is None or not expr.strip():
        return None
    match = _FILTER_RE.fullmatch(expr.strip())
    if match is None:
        raise ScimError(
            400,
            "Unsupported filter: EQ only, one clause, one of "
            'userName / emails.value / externalId (e.g. userName eq "jdoe")',
        )
    return _FILTER_FIELDS[match.group(1).lower()], match.group(2)


# --- mapping: Identity -> SCIM User resource ---


def _scim_timestamp(dt) -> str:
    # Naive-UTC by contract; SCIM meta timestamps get the "Z" suffix.
    return dt.isoformat() + "Z" if dt is not None else None


def identity_to_scim(identity) -> dict:
    """Render an Identity row as a SCIM User resource (spec: Resource mapping).

    id = externalId = employee_id (D3: the IdP's declared stable key,
    stored verbatim). userName falls back email, then f"user_{employee_id}".
    phoneNumbers never emitted (v1 placeholder designed out).
    """
    employee_id = identity.employee_id
    user_name = identity.username or identity.email or f"user_{employee_id}"
    resource: dict = {
        "schemas": [USER_SCHEMA],
        "id": employee_id,
        "externalId": employee_id,
        "userName": user_name,
        "active": bool(identity.is_active),
        "meta": {
            "resourceType": "User",
            "created": _scim_timestamp(identity.created_at),
            "lastModified": _scim_timestamp(identity.updated_at),
        },
    }
    if identity.first_name or identity.last_name:
        name: dict = {}
        if identity.first_name:
            name["givenName"] = identity.first_name
        if identity.last_name:
            name["familyName"] = identity.last_name
        resource["name"] = name
    display = " ".join(p for p in (identity.first_name, identity.last_name) if p)
    if display:
        resource["displayName"] = display
    if identity.email:
        resource["emails"] = [{"value": identity.email, "type": "work", "primary": True}]
    if identity.job_title:
        resource["title"] = identity.job_title
    if identity.department:
        resource["department"] = identity.department
    return resource


# --- mapping: SCIM User payload -> Identity field dict ---


def _primary_email(payload: dict) -> str | None:
    emails = payload.get("emails")
    if not isinstance(emails, list):
        return None
    values = [e for e in emails if isinstance(e, dict) and e.get("value")]
    if not values:
        return None
    for entry in values:
        if entry.get("primary"):
            return entry["value"]
    return values[0]["value"]


def _name_parts(payload: dict) -> tuple[str | None, str | None]:
    name = payload.get("name")
    if not isinstance(name, dict):
        return None, None
    given = name.get("givenName")
    family = name.get("familyName")
    return (given or None, family or None) if (given or family) else (None, None)


def scim_to_identity_fields(payload: dict) -> dict:
    """Map a SCIM User create/PUT body onto writable Identity columns.

    Spec "In" mapping: userName -> username, primary-or-first email -> email,
    name.givenName/familyName -> first/last, title -> job_title, department,
    active -> is_active. displayName parsed ONLY when name parts are absent
    (split on first space; a single token becomes first_name - it is the
    only name given). Manager and phone ignored (non-goals).
    """
    fields: dict = {}
    if "userName" in payload and payload.get("userName"):
        fields["username"] = payload["userName"]
    email = _primary_email(payload)
    if email:
        fields["email"] = email
    given, family = _name_parts(payload)
    if given is None and family is None:
        display = payload.get("displayName")
        if isinstance(display, str) and display.strip():
            head, _, tail = display.strip().partition(" ")
            given = head or None
            family = tail or None
    if given is not None:
        fields["first_name"] = given
    if family is not None:
        fields["last_name"] = family
    if "title" in payload and payload.get("title"):
        fields["job_title"] = payload["title"]
    if "department" in payload and payload.get("department"):
        fields["department"] = payload["department"]
    if "active" in payload and payload["active"] is not None:
        fields["is_active"] = bool(payload["active"])
    return fields
# --- PATCH normalization (RFC 7644 3.5.2, replace-only subset) ---

# Attribute path -> writable SCIM User attribute. Paths are case-insensitive
# (RFC 7644 3.10); matched against a lowercased path.
_PATCH_PATHS = {
    "active": "active",
    "username": "userName",
    "displayname": "displayName",
    "emails": "emails",
    "title": "title",
    "department": "department",
    "name.givenname": "name.givenName",
    "name.familyname": "name.familyName",
}


def normalize_patch(payload: dict) -> dict:
    """Fold a PATCH body into the same shape scim_to_identity_fields eats.

    Two accepted shapes per operation:
    - path form: {"op": "replace", "path": "active", "value": false}
    - path-less form (the Okta deprovisioning shape): {"op": "replace",
      "value": {"active": false}} - value is an object keyed by attribute.

    Returns a SCIM-User-shaped dict (e.g. {"active": False}) that feeds
    scim_to_identity_fields; empty dict = nothing writable arrived. add /
    remove / unknown ops and any path outside the subset are 400s
    (advertised nowhere; the SPC says patch supported, not universal).
    """
    operations = payload.get("Operations")
    if not isinstance(operations, list) or not operations:
        raise ScimError(400, "PATCH requires a non-empty Operations array")

    merged: dict = {}
    for index, op in enumerate(operations):
        if not isinstance(op, dict):
            raise ScimError(400, f"Operations[{index}] must be an object")
        kind = str(op.get("op", "")).lower()
        if kind != "replace":
            raise ScimError(400, f"Unsupported op '{op.get('op')}': replace only")
        path = op.get("path")
        value = op.get("value")
        if path is not None:
            attribute = _PATCH_PATHS.get(str(path).lower())
            if attribute is None:
                raise ScimError(400, f"Unsupported path '{path}'")
            merged[attribute] = value
        elif isinstance(value, dict):
            for raw_key, sub_value in value.items():
                attribute = _PATCH_PATHS.get(str(raw_key).lower())
                if attribute is None:
                    raise ScimError(400, f"Unsupported path '{raw_key}'")
                merged[attribute] = sub_value
        else:
            raise ScimError(
                400, "replace without path requires an object value keyed by attribute"
            )
    return merged

